name: Extract patterns and publish them on DX Hub Knowledge Base

on:
  workflow_dispatch:

jobs:
  extract:
    name: Extract patterns from markdown files into JSON file
    runs-on: ubuntu-latest
    env:
      DXHUB_KB_API_URL: ${{ vars.DXHUB_KB_API_URL }}
      DXHUB_KB_API_KEY: ${{ secrets.DXHUB_KB_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.9
          cache: yarn
          cache-dependency-path: 'avalia/scripts'
      - name: Install dependencies
        run: yarn install
        working-directory: ./avalia/scripts
      - name: Run extraction script
        run: node extract-and-publish.js
        working-directory: ./avalia/scripts
      - name: Check generated JSON
        run: cat patterns.json
        working-directory: ./avalia/scripts
